# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kkdFileId', models.IntegerField()),
                ('fileName', models.CharField(max_length=1000)),
                ('fileTypec', models.CharField(max_length=20)),
                ('fileSize', models.CharField(max_length=100)),
                ('isDownload', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kkdBookId', models.IntegerField()),
                ('bookName', models.CharField(max_length=100)),
                ('clickNum', models.IntegerField()),
                ('doubanImgSrc', models.CharField(max_length=1000)),
                ('doubanBookUrl', models.CharField(max_length=1000)),
                ('detail_tag_id_2', models.CharField(max_length=100000)),
                ('detail_tag_id_3', models.CharField(max_length=100000)),
                ('detail_tag_id_4', models.CharField(max_length=100000)),
                ('detail_tag_id_5', models.CharField(max_length=100000)),
                ('detail_tag_id_6', models.CharField(max_length=100000)),
                ('detail_tag_id_7', models.CharField(max_length=100000)),
                ('content', models.CharField(max_length=10000)),
                ('bookType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbookspider.BookType')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writerName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='kbook',
            name='tag',
            field=models.ManyToManyField(to='kbookspider.Tag'),
        ),
        migrations.AddField(
            model_name='kbook',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbookspider.Writer'),
        ),
        migrations.AddField(
            model_name='bookfile',
            name='kkdBook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbookspider.Kbook'),
        ),
    ]
